name: Deploy to Hostinger

on:
  push:
    branches: [main-nextjs]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Build das imagens com docker-compose
        run: docker compose build

      - name: Push para o Docker Hub
        run: docker compose push
